name: instagram_app_sky
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  hooks_riverpod: ^2.1.1
  uuid: ^3.0.6
  cloud_firestore: ^4.0.4
  firebase_storage: ^11.0.4
  firebase_auth: ^4.1.1
  font_awesome_flutter: ^10.2.1
  flutter_facebook_auth: ^5.0.1
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6
  image: ^3.2.2
  flutter_hooks: ^0.18.5+1
  collection: ^1.16.0
  intl: ^0.17.0
  video_thumbnail: ^0.5.3
  video_player: ^2.4.7
  lottie: ^1.4.3
  share_plus: ^6.2.0
  url_launcher: ^6.1.6
  riverpod_annotation: ^1.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
