// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWL_C-fCnFfbjBTCB7cdZKtGoUyC-qWTA',
    appId: '1:1097511783274:web:577f34156b2fe1a986f313',
    messagingSenderId: '1097511783274',
    projectId: 'instagram-sky',
    authDomain: 'instagram-sky.firebaseapp.com',
    storageBucket: 'instagram-sky.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ahk0tdoz-GzDhkobhH5pdNP4Y9XJWsw',
    appId: '1:1097511783274:android:60bc67a2b52936ac86f313',
    messagingSenderId: '1097511783274',
    projectId: 'instagram-sky',
    storageBucket: 'instagram-sky.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4PEb1tZ28zQqt6N6oG06C5_AhJ9Z7QqQ',
    appId: '1:1097511783274:ios:883bc7772184193186f313',
    messagingSenderId: '1097511783274',
    projectId: 'instagram-sky',
    storageBucket: 'instagram-sky.appspot.com',
    iosClientId: '1097511783274-pqo0lhb940e095mscog38sumq7r587qm.apps.googleusercontent.com',
    iosBundleId: 'sky.sky.instagramAppSky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4PEb1tZ28zQqt6N6oG06C5_AhJ9Z7QqQ',
    appId: '1:1097511783274:ios:883bc7772184193186f313',
    messagingSenderId: '1097511783274',
    projectId: 'instagram-sky',
    storageBucket: 'instagram-sky.appspot.com',
    iosClientId: '1097511783274-pqo0lhb940e095mscog38sumq7r587qm.apps.googleusercontent.com',
    iosBundleId: 'sky.sky.instagramAppSky',
  );
}
